### ISSUE TITLE
Pull down for data has a misspelling for temperature

### ISSUE THREAD

**Issue by hangtime79** [IBMPredictiveAnalytics/Weather_Underground_Import#1]
In the Data: dialog drop down the case of Minimum Temperature, Temperature is misspelled.

![image](https://cloud.githubusercontent.com/assets/2651677/13056462/744f9e86-d3e3-11e5-8da4-5985605be729.png)

**Comment by gfilla** [comment]
Updated in .cfe available in source code folder.  Thanks for the heads up!
