### ISSUE TITLE
where is the  CDB folder  for Mac?

### ISSUE THREAD

**Issue by DataHe** [IBMPredictiveAnalytics/Weather_Underground_Import#2]
I can't find any CDB folder in mac spss modeler

**Comment by gfilla** [comment]
@wujiazhong do you know the default file path to CDB on Mac?

**Comment by wujiazhong** [comment]
/Library/Application Support/IBM/SPSS/Statistics/24/CustomDialogs

**Comment by DataHe** [comment]
I can‘t find that folder in my mac
BTW, the "Application support" for IBM software is an independent folder which named "IBM Application Support".
I also searching that folder, I can't find the CDB folder
 
 
----- Original message -----From: Jia Zhong Wu notifications@github.comTo: IBMPredictiveAnalytics/Weather_Underground_Import Weather_Underground_Import@noreply.github.comCc: Wei WW He/China/IBM@IBMCNSubject: Re: [IBMPredictiveAnalytics/Weather_Underground_Import] where is the CDB folder for Mac? (#2)Date: Tue, Apr 12, 2016 9:32 AM 
/Library/Application Support/IBM/SPSS/Statistics/24/CustomDialogs

**Comment by wujiazhong** [comment]
Sorry, I made a mistake. It is in /User/XXX/Library/Application Support/IBM/SPSS/Modeler/18

**Comment by DataHe** [comment]
cool! the CDB folder is there!  I copy the cfe file into it and restart modeler, it working! many thanks!
 
 
----- Original message -----From: Jia Zhong Wu notifications@github.comTo: IBMPredictiveAnalytics/Weather_Underground_Import Weather_Underground_Import@noreply.github.comCc: Wei WW He/China/IBM@IBMCNSubject: Re: [IBMPredictiveAnalytics/Weather_Underground_Import] where is the CDB folder for Mac? (#2)Date: Tue, Apr 12, 2016 10:20 AM 
Sorry, I made a mistake. It is in /User/XXX/Library/Application Support/IBM/SPSS/Modeler/18

**Comment by heweihe** [comment]
Hi,Can I get some help from you?

I am mac modeler 18 ,R 3.2.2, and essential for R also was installed.
but my stream file worked out nothing bug some NAs , below are some logs

Could you guide me how to fix it？






He Wei (何威)
Big Data Analyst
BigData and Analytics
IBM Systems Lab Services (GCG)
Mobile: (86) 13942699329  Mail: heweihe@cn.ibm.com
No.28 Hong Chuan East Road, Hi-Tech Zone District, Dalian, China (116044)



From:   Wei WW He/China/IBM
To:     
reply@reply.github.com
Cc:     Weather_Underground_Import@noreply.github.com
Date:   2016-04-12 上午 11:06
Subject:        Re: [IBMPredictiveAnalytics/Weather_Underground_Import] 
where is the  CDB folder  for Mac? (#2)



cool! the CDB folder is there!  I copy the cfe file into it and restart 
modeler, it working! many thanks! 
 
 
----- Original message -----
