### ISSUE TITLE
Error URL does not seem to exist:

### ISSUE THREAD

**Issue by adolfest** [IBMPredictiveAnalytics/Weather_Underground_Import#3]
I used the node that was developed to take advantage of weatherData package but it returned me the same error every time even when I tried whit the SPSS Modeler example stream that is available in github. This is the error:

bmspsscfdatamodel.SetDataModel(modelerDataModel)
ibmspsscfdata.SetData(modelerData)
}******************************************************
Loading required package: weatherData
[1] "weatherData is loaded correctly"
Loading required package: plyr
[1] "plyr is loaded correctly"
 [1] "55AK" "AZ17" "CL33" "IAD"  "X59"  "EFW"  "LL45" "3II1" "MHK"  "ASD" 
[11] "3GM"  "23MN" "MMGL" "NC49" "ICAO" "2Q9"  "93OH" "OK62" "60OR" "PS61"
[21] "MEM"  "0TA3" "JWY"  "4XS8" "WN24" "0WI5"
URL does not seem to exist: http://www.wunderground.com/history/airport/55AK/2015/12/31/DailyHistory.html?format=1
The original error message:
cannot open the connectionURL does not seem to exist: http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=55AK&month=12&day=31&year=2015&format=1

It may seem a mistake of incorrect station code but Ialso used a station code that retrieves data from the URL (MMGL) but the result didn’t change, the same error came up.
https://www.wunderground.com/history/airport/MMGL/2015/12/31/DailyHistory.html?format=1

**Comment by Wenpei** [comment]
R 3.2.5 fix `readLines` issues, please update to new version. Please refer to #4 for more detail.

Weather Underground API doesnot support Airport code "55AK", but support "MMGL"
![result](https://cloud.githubusercontent.com/assets/6813734/20052611/b9b616dc-a50f-11e6-9413-a9b52b83f0e8.jpg)

**Comment by Wenpei** [comment]
I plan to do some cleanup for our example code to fit api requirment. But actually, I don't know what's the different for those two code.
Any thought for this, @gfilla .
