### ISSUE TITLE
Extension returning only null values

### ISSUE THREAD

**Issue by hNosse** [IBMPredictiveAnalytics/Weather_Underground_Import#4]
When trying to recreate the example stream provided in GitHub, the extension node is returning only null values. No error messages, and on the first run the extension installed the needed R packages successfully. I am using R version 3.2.0 and SPSS Modeler 18.0.

**Comment by gfilla** [comment]
@Wenpei Do you have time to look into this?

**Comment by Wenpei** [comment]
It looks R 3.2.0 has issues to run below code

```
final_url <- "http://www.wunderground.com/history/airport/MMGL/2015/12/31/DailyHistory.html?format=1"
readLines(url(final_url)
```

This code works fine in R 3.2.5.  And can get result successful.

Please update to R 3.2.5, and try again.
